Iniciando montagem da lista com nomes dos arquivos de áudio e transcrições
Efetuando o monitoramento do processo PID 10486
Status atual do processo de PID 10486: running
[Parallel(n_jobs=4)]: Using backend MultiprocessingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  12 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 2040 tasks      | elapsed:    0.8s
[Parallel(n_jobs=4)]: Done 4316 out of 4316 | elapsed:    1.6s finished
Tempo de processamento da vetorizacao 0.26304
[array([], dtype='<U16')]
Iniciando atualização de caminhos para arquivos de áudio
Iniciando conversão dos audios em espectogramas e log_energy
[Parallel(n_jobs=4)]: Using backend MultiprocessingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  12 tasks      | elapsed:    0.4s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:    2.4s
[Parallel(n_jobs=4)]: Done 300 tasks      | elapsed:    6.2s
[Parallel(n_jobs=4)]: Done 552 tasks      | elapsed:   11.3s
[Parallel(n_jobs=4)]: Done 876 tasks      | elapsed:   17.4s
[Parallel(n_jobs=4)]: Done 1272 tasks      | elapsed:   25.7s
[Parallel(n_jobs=4)]: Done 1740 tasks      | elapsed:   35.0s
[Parallel(n_jobs=4)]: Done 2280 tasks      | elapsed:   45.1s
[Parallel(n_jobs=4)]: Done 2892 tasks      | elapsed:   56.4s
[Parallel(n_jobs=4)]: Done 3576 tasks      | elapsed:  1.2min
[Parallel(n_jobs=4)]: Done 4316 out of 4316 | elapsed:  1.4min finished
<treinamento.audio.Audio object at 0x7ff462956780>
Tempo total de pré-processamento dos dados:  49.602603 segundos
Process Process-2:
Traceback (most recent call last):
  File "/home/usuario/mestrado/yorubaSpeechRecognition/environmentYorubaSpeechRecognition/lib/python3.6/site-packages/psutil/_common.py", line 449, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usuario/mestrado/yorubaSpeechRecognition/environmentYorubaSpeechRecognition/lib/python3.6/site-packages/psutil/_pslinux.py", line 1515, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/usuario/mestrado/yorubaSpeechRecognition/environmentYorubaSpeechRecognition/lib/python3.6/site-packages/psutil/_common.py", line 452, in wrapper
    return fun(self)
  File "/home/usuario/mestrado/yorubaSpeechRecognition/environmentYorubaSpeechRecognition/lib/python3.6/site-packages/psutil/_pslinux.py", line 1557, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/home/usuario/mestrado/yorubaSpeechRecognition/environmentYorubaSpeechRecognition/lib/python3.6/site-packages/psutil/_common.py", line 713, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/10486/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/usuario/mestrado/yorubaSpeechRecognition/monitoramento/monitoramento_PROPRIETARY.py", line 147, in monitor
    pr_status = pr.status()
  File "/home/usuario/mestrado/yorubaSpeechRecognition/environmentYorubaSpeechRecognition/lib/python3.6/site-packages/psutil/__init__.py", line 699, in status
    return self._proc.status()
  File "/home/usuario/mestrado/yorubaSpeechRecognition/environmentYorubaSpeechRecognition/lib/python3.6/site-packages/psutil/_pslinux.py", line 1515, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/usuario/mestrado/yorubaSpeechRecognition/environmentYorubaSpeechRecognition/lib/python3.6/site-packages/psutil/_pslinux.py", line 2020, in status
    letter = self._parse_stat_file()['status']
  File "/home/usuario/mestrado/yorubaSpeechRecognition/environmentYorubaSpeechRecognition/lib/python3.6/site-packages/psutil/_pslinux.py", line 1522, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=10486)
